name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish-Linux-x64
      run: dotnet publish ScriptCompiler/ScriptCompiler.csproj --configuration Release --runtime linux-x64 --self-contained true -p:PublishSingleFile=true -p:DebugType=embedded --output linux-x64/
    - name: Upload publish output
      uses: actions/upload-artifact@v2
      with:
        name: Linux-x64
        path: /home/runner/work/ScriptCompiler/ScriptCompiler/linux-x64/
